name: open_llm_studio_api
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^7.6.0
  either_dart: ^1.0.0
  firebase_database: ^10.2.3
  uuid: ^3.0.7
  dart_openai: ^4.0.0
  cloud_firestore: ^4.8.3

  llm_chat:
    git:
      url: https://github.com/josedoes/llm_chat
      ref: master


dev_dependencies:
  flutter_test:
    sdk: flutter

  fake_cloud_firestore:
  firebase_storage_mocks: ^0.6.1
  flutter_lints: ^2.0.2
  json_serializable: ^6.7.1
  mocktail:

flutter:
  uses-material-design: true
